on:
  workflow_dispatch:
    inputs:
      releaseVersion:
        description: "Provide git tag version like 1.13.5"
        required: true
jobs:  
  testvariables:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Create commit_id & version environment variables
        working-directory: .
        run: |
          commitId=$(git rev-parse --short HEAD)
          echo "commitId=$commitId" >> $GITHUB_ENV
          echo "version=${GITHUB_REF#refs/*/}" >> $GITHUB_ENV
      - name: Print variables
        run: |
          echo "${{ env.commitId }}"
          echo "${{ env.version }}"
          echo "${{ github.ref_name }}
